"""initial

Revision ID: 856d0451be3e
Revises: 
Create Date: 2025-05-02 02:19:50.994107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '856d0451be3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_value_key', 'categories', type_='unique')
    op.add_column('products', sa.Column('photos', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('availability', sa.String(), nullable=True, server_default='в наличии'))
    op.alter_column('products', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('shops', sa.Column('tg', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('whatsapp', sa.String(), nullable=True))
    op.alter_column('shops', 'addresses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='contains {phone: int, address: str}',
               existing_nullable=True)
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.alter_column('shops', 'addresses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='contains {phone: int, address: str}',
               existing_nullable=True)
    op.drop_column('shops', 'whatsapp')
    op.drop_column('shops', 'tg')
    op.alter_column('products', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'availability')
    op.drop_column('products', 'photos')
    op.create_unique_constraint('categories_value_key', 'categories', ['value'])
    # ### end Alembic commands ###
